const SUPABASE_URL='https://jivaaripugjdpxjvjnsu.supabase.co';
const SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFyaXAiLCJyZWYiOiJqaXZhYXJpcHVnamRweGp2am5zdSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzg1NjQ2NzMyLCJleHAiOjIxMDEyMjI3MzJ9.N60Xb1PqqPo12HdKEzPc4qCp1aFvVzwZz4VG04q_Es4';
const WHATSAPP='59177057379';
const CATEGORIES=['Recargas por ID','Recargas por Cuenta','Streaming','Gift Cards'];
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});

let inventory=[];
let category='Recargas por ID';
let cart=loadCart();
let session=null;
let profile=null;
let admin=false;
let adminTab='topups';
let lastQrOrder=null;

const $=id=>document.getElementById(id);
const money=n=>`Bs ${Number(n||0).toLocaleString('es-BO',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const dateFmt=v=>v?new Intl.DateTimeFormat('es-BO',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—';
const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'');

function showNotice(el,msg,type=''){el.textContent=msg;el.className=`notice ${type}`.trim();el.classList.remove('hidden')}
function hideNotice(el){el.classList.add('hidden')}
function openModal(id){$(id).classList.add('open');$(id).setAttribute('aria-hidden','false')}
function closeModal(id){$(id).classList.remove('open');$(id).setAttribute('aria-hidden','true')}
function loadCart(){try{const x=JSON.parse(localStorage.getItem('fs_cart_v2')||'[]');return Array.isArray(x)?x.filter(i=>i&&i.product_id&&i.quantity>0):[]}catch{return[]}}
function saveCart(){localStorage.setItem('fs_cart_v2',JSON.stringify(cart));renderCartCounters()}
function renderCartCounters(){const n=cart.reduce((a,i)=>a+Number(i.quantity||0),0);$('cartCount').textContent=n;$('cartInlineCount').textContent=n}
function currentProduct(id){return inventory.find(p=>String(p.id)===String(id))}
function cartVisualTotal(){return cart.reduce((a,i)=>{const p=currentProduct(i.product_id);return a+(p?Number(p.precio||0)*i.quantity:0)},0)}

function canonicalGame(name){const k=normalize(name);if(k==='magicchessgogo'||k==='magicchess')return'Magic Chess';if(k==='mobilelegendsbangbang'||k==='mobilelegends')return'Mobile Legends: Bang Bang';return String(name||'Sin nombre').trim()}
function logoDomain(name){const k=normalize(name);const rules=[['freefire','ff.garena.com'],['mobilelegends','mobilelegends.com'],['pubg','pubgmobile.com'],['genshin','genshin.hoyoverse.com'],['wuthering','wutheringwaves.kurogames.com'],['honorofking','honorofkings.com'],['bloodstrike','blood-strike.com'],['clashofclans','supercell.com'],['clashroyale','supercell.com'],['fortnite','fortnite.com'],['roblox','roblox.com'],['minecraft','minecraft.net'],['valorant','playvalorant.com'],['steam','steampowered.com'],['netflix','netflix.com'],['disney','disneyplus.com'],['hbomax','max.com'],['primevideo','primevideo.com'],['vix','vix.com'],['spotify','spotify.com'],['crunchyroll','crunchyroll.com']];return(rules.find(r=>k.includes(r[0]))||[])[1]||''}
function logoUrl(name){const d=logoDomain(name);return d?`https://www.google.com/s2/favicons?sz=128&domain_url=https://${d}`:''}

function navigate(view){if(['wallet','pedidos','perfil'].includes(view)&&!session){openModal('authModal');return}if(view==='admin'&&!admin)return;document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));const target=$(`view-${view}`);if(target)target.classList.add('active');document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===view));window.scrollTo({top:0,behavior:'auto'});if(view==='wallet')loadWallet();if(view==='pedidos')loadOrders();if(view==='perfil')renderProfile();if(view==='admin')loadAdmin()}

function renderCategoryTabs(){const box=$('categoryTabs');box.innerHTML=CATEGORIES.map(c=>`<button class="${c===category?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{category=b.dataset.cat;renderCategoryTabs();renderCatalog()})}

function productGroups(items){const groups={};items.forEach(p=>{const n=canonicalGame(p.juego);(groups[n]??=[]).push(p)});return Object.entries(groups).sort((a,b)=>a[0].localeCompare(b[0],'es',{sensitivity:'base'}))}
function gameCard(game,products,compact=false){const logo=logoUrl(game);const rows=compact?'':`<div class="package-list">${products.sort((a,b)=>Number(a.precio)-Number(b.precio)).map(p=>`<div class="package-row"><div class="package-name">${esc(p.paquete)}</div><span class="package-price">${money(p.precio)}</span><button class="add-btn" data-add="${p.id}">+ Carrito</button></div>`).join('')}</div>`;return `<article class="game-card"><div class="game-card-head">${logo?`<img class="game-logo" src="${esc(logo)}" alt="${esc(game)}" loading="lazy" decoding="async">`:`<div class="game-logo" aria-hidden="true"></div>`}<div class="game-info"><b>${esc(game)}</b><small>${products.length} paquete${products.length===1?'':'s'} disponible${products.length===1?'':'s'}</small></div><div class="game-actions">${compact?`<button class="plus-btn" data-open-category="${esc(category)}">+</button>`:''}</div></div>${rows}</article>`}

function bindAddButtons(root=document){root.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addToCart(b.dataset.add));root.querySelectorAll('[data-open-category]').forEach(b=>b.onclick=()=>navigate('tienda'))}
function renderFeatured(){const active=inventory.filter(p=>p.activo===true);const preferred=['Mobile Legends: Bang Bang','Free Fire','PUBG','Clash Of Clans','Wuthering'];const groups=productGroups(active);const picked=[...groups].sort((a,b)=>{const ai=preferred.findIndex(x=>normalize(a[0]).includes(normalize(x)));const bi=preferred.findIndex(x=>normalize(b[0]).includes(normalize(x)));return(ai<0?99:ai)-(bi<0?99:bi)}).slice(0,4);$('featuredList').innerHTML=picked.length?picked.map(([g,p])=>gameCard(g,p,true)).join(''):'<div class="auth-required">No hay productos destacados.</div>';bindAddButtons($('featuredList'))}
function renderCatalog(){const items=inventory.filter(p=>p.activo===true&&p.categoria===category);const groups=productGroups(items);$('categoryEyebrow').textContent=category.toUpperCase();$('catalogMeta').textContent=`${groups.length} juego${groups.length===1?'':'s'} · ${items.length} paquete${items.length===1?'':'s'}`;$('catalogList').innerHTML=groups.length?groups.map(([g,p])=>gameCard(g,p)).join(''):'<div class="auth-required"><b>Sin productos disponibles</b>Esta sección no tiene productos activos en este momento.</div>';bindAddButtons($('catalogList'))}

async function loadProducts(){const{data,error}=await sb.from('productos').select('id,juego,paquete,categoria,precio,activo').eq('activo',true).order('juego').order('precio');if(error){$('catalogList').innerHTML=`<div class="notice error">No se pudo cargar el catálogo: ${esc(error.message)}</div>`;return}inventory=data||[];renderCategoryTabs();renderCatalog();renderFeatured();renderCart()}

function addToCart(id){const p=currentProduct(id);if(!p)return;const x=cart.find(i=>String(i.product_id)===String(id));if(x)x.quantity=Math.min(99,x.quantity+1);else cart.push({product_id:Number(id),quantity:1});saveCart();renderCart();}
function setQty(id,delta){const x=cart.find(i=>String(i.product_id)===String(id));if(!x)return;x.quantity+=delta;if(x.quantity<=0)cart=cart.filter(i=>String(i.product_id)!==String(id));x.quantity=Math.min(99,x.quantity);saveCart();renderCart()}
function renderCart(){const box=$('cartItems');cart=cart.filter(i=>currentProduct(i.product_id));saveCart();if(!cart.length){box.innerHTML='<div class="auth-required"><b>Tu carrito está vacío</b>Agrega productos desde la tienda.</div>';$('cartTotal').textContent=money(0);return}box.innerHTML=cart.map(i=>{const p=currentProduct(i.product_id);return `<div class="record"><div class="record-top"><div><b>${esc(canonicalGame(p.juego))}</b><small>${esc(p.paquete)}</small></div><b>${money(Number(p.precio)*i.quantity)}</b></div><div class="admin-actions"><button data-minus="${p.id}">−</button><span class="status">x${i.quantity}</span><button data-plus="${p.id}">+</button><button data-remove="${p.id}">Quitar</button></div></div>`}).join('');$('cartTotal').textContent=money(cartVisualTotal());box.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>setQty(b.dataset.minus,-1));box.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>setQty(b.dataset.plus,1));box.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(i=>String(i.product_id)!==String(b.dataset.remove));saveCart();renderCart()})}
function rpcItems(){return cart.map(i=>({product_id:Number(i.product_id),quantity:Number(i.quantity)}))}

async function checkout(method){hideNotice($('checkoutResult'));if(!session){closeModal('cartModal');openModal('authModal');return}if(!cart.length){showNotice($('checkoutResult'),'Tu carrito está vacío.','error');return}const fn=method==='wallet'?'create_wallet_order':'create_qr_order';const{data,error}=await sb.rpc(fn,{p_items:rpcItems(),p_customer_note:null});if(error){const map={INSUFFICIENT_WALLET_BALANCE:'Saldo insuficiente en French Wallet.',WALLET_BLOCKED:'Tu Wallet no está disponible.',INVALID_OR_INACTIVE_PRODUCT:'Uno de los productos cambió o ya no está disponible. Actualiza el catálogo.',AUTH_REQUIRED:'Debes iniciar sesión.'};showNotice($('checkoutResult'),map[error.message]||error.message,'error');return}if(!data?.ok){showNotice($('checkoutResult'),'No se pudo crear el pedido.','error');return}cart=[];saveCart();renderCart();if(method==='wallet'){showNotice($('checkoutResult'),`Pedido ${data.order_code} creado. Total ${money(data.total)}. Estado: ${statusLabel(data.status)}.`,'success');await loadWallet();}else{lastQrOrder=data;closeModal('cartModal');$('qrOrderCode').textContent=`Pedido ${data.order_code}`;$('qrOrderTotal').textContent=`Total: ${money(data.total)}`;openModal('qrModal')}await loadOrders()}

async function signIn(){hideNotice($('loginMessage'));const email=$('loginEmail').value.trim();const password=$('loginPassword').value;if(!email||!password){showNotice($('loginMessage'),'Completa correo y contraseña.','error');return}const{error}=await sb.auth.signInWithPassword({email,password});if(error){showNotice($('loginMessage'),'No se pudo iniciar sesión. Revisa tus datos.','error');return}closeModal('authModal')}
async function signUp(){hideNotice($('loginMessage'));const email=$('loginEmail').value.trim();const password=$('loginPassword').value;if(!email||password.length<8){showNotice($('loginMessage'),'Usa un correo válido y una contraseña de al menos 8 caracteres.','error');return}const{data,error}=await sb.auth.signUp({email,password});if(error){showNotice($('loginMessage'),error.message,'error');return}if(data.session){closeModal('authModal')}else showNotice($('loginMessage'),'Cuenta creada. Revisa tu correo si Supabase solicita confirmación.','success')}
async function signOut(){await sb.auth.signOut();navigate('inicio')}

async function refreshSession(newSession=null){session=newSession??(await sb.auth.getSession()).data.session;profile=null;admin=false;if(session){const[{data:p},{data:a}]=await Promise.all([sb.from('profiles').select('id,email,display_name').eq('id',session.user.id).maybeSingle(),sb.rpc('is_admin')]);profile=p||{email:session.user.email,display_name:null};admin=a===true;$('authButton').textContent=profile.display_name||profile.email||'Mi cuenta';$('logoutButton').classList.remove('hidden');$('openAdmin').classList.toggle('hidden',!admin)}else{$('authButton').textContent='Iniciar sesión';$('logoutButton').classList.add('hidden');$('openAdmin').classList.add('hidden')}renderProfile()}
function renderProfile(){if(!session){$('profileName').textContent='Cliente';$('profileEmail').textContent='Sin sesión';return}$('profileName').textContent=profile?.display_name||'Cliente FRENCH STORE';$('profileEmail').textContent=profile?.email||session.user.email||''}

async function loadWallet(){if(!session)return;const[bal,acc,topups,tx]=await Promise.all([sb.rpc('get_my_wallet_balance'),sb.from('wallet_accounts').select('status,currency').eq('user_id',session.user.id).maybeSingle(),sb.from('wallet_topup_requests').select('id,amount,status,payment_reference,created_at,expires_at').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(20),sb.from('wallet_transactions').select('id,transaction_type,amount,description,created_at').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(30)]);$('walletBalance').textContent=money(bal.data||0);$('walletStatus').textContent=acc.data?`Wallet ${acc.data.status} · ${acc.data.currency}`:'Wallet no encontrada';$('topupHistory').innerHTML=(topups.data||[]).map(t=>recordTopup(t)).join('')||'<div class="record"><small>Aún no tienes solicitudes.</small></div>';$('walletHistory').innerHTML=(tx.data||[]).map(t=>`<div class="record"><div class="record-top"><div><b>${esc(t.description||t.transaction_type)}</b><small>${dateFmt(t.created_at)}</small></div><b>${Number(t.amount)>=0?'+':''}${money(t.amount)}</b></div></div>`).join('')||'<div class="record"><small>Aún no tienes movimientos.</small></div>'}
function recordTopup(t){return `<div class="record"><div class="record-top"><div><b>${money(t.amount)}</b><small>${esc(t.payment_reference||'Sin referencia')} · ${dateFmt(t.created_at)}</small></div>${statusHtml(t.status)}</div><div class="record-meta"><span>Vence: ${dateFmt(t.expires_at)}</span></div></div>`}
async function requestTopup(){hideNotice($('topupResult'));const amount=Number($('topupAmount').value);if(!amount||amount<=0){showNotice($('topupResult'),'Introduce un monto válido.','error');return}const{data,error}=await sb.rpc('request_wallet_topup_v2',{p_amount:amount});if(error){showNotice($('topupResult'),error.message,'error');return}showNotice($('topupResult'),`Solicitud creada: ${data.payment_reference}. Paga exactamente ${money(data.amount)} antes de ${dateFmt(data.expires_at)}.`,'success');$('topupAmount').value='';loadWallet()}

const LABELS={PENDING_PAYMENT:'Pendiente de pago',PAID:'Pagado',MANUAL_REQUIRED:'Requiere atención manual',AWAITING_CODE:'Esperando código',PROCESSING:'Procesando',DELIVERED:'Entregado',ERROR:'Error',PENDING:'Pendiente',APPROVED:'Aprobado',REJECTED:'Rechazado',AMBIGUOUS:'Revisión Admin',MATCHED:'Vinculado'};
function statusLabel(s){return LABELS[s]||String(s||'').replaceAll('_',' ')}
function statusHtml(s){const cls=['APPROVED','DELIVERED','MATCHED','PAID'].includes(s)?'ok':['ERROR','REJECTED'].includes(s)?'bad':'warn';return `<span class="status ${cls}">${esc(statusLabel(s))}</span>`}
async function loadOrders(){if(!session)return;const{data,error}=await sb.from('orders').select('id,order_code,status,payment_method,total_amount,currency,created_at,updated_at,customer_note').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(50);$('ordersList').innerHTML=error?`<div class="notice error">${esc(error.message)}</div>`:(data||[]).map(o=>`<div class="record"><div class="record-top"><div><b>${esc(o.order_code)}</b><small>${dateFmt(o.created_at)} · ${esc(o.payment_method)}</small></div>${statusHtml(o.status)}</div><div class="record-meta"><b>${money(o.total_amount)}</b>${o.customer_note?`<span>${esc(o.customer_note)}</span>`:''}</div></div>`).join('')||'<div class="record"><small>Aún no tienes pedidos.</small></div>'}

async function loadAdmin(){if(!admin)return;$('adminContent').innerHTML='<div class="record"><small>Cargando…</small></div>';if(adminTab==='topups'){const{data,error}=await sb.from('wallet_topup_requests').select('id,user_id,amount,status,payment_reference,created_at,expires_at').eq('status','PENDING').order('created_at',{ascending:true}).limit(100);$('adminContent').innerHTML=error?err(error):(data||[]).map(t=>`<div class="record"><div class="record-top"><div><b>${money(t.amount)} · ${esc(t.payment_reference||'')}</b><small>${dateFmt(t.created_at)}</small></div>${statusHtml(t.status)}</div><div class="admin-actions"><button data-topup-action="APPROVE" data-id="${t.id}">Aprobar</button><button data-topup-action="REJECT" data-id="${t.id}">Rechazar</button></div></div>`).join('')||empty('No hay cargas pendientes.');bindAdminActions()}else if(adminTab==='payments'){const{data,error}=await sb.from('bank_payment_events').select('id,amount,currency,origin_name,origin_bank,ach_order_number,transaction_at,match_status,match_reason').eq('match_status','AMBIGUOUS').order('transaction_at',{ascending:false}).limit(100);$('adminContent').innerHTML=error?err(error):(data||[]).map(p=>`<div class="record"><div class="record-top"><div><b>${money(p.amount)} · ${esc(p.origin_name||'Origen no identificado')}</b><small>${esc(p.origin_bank||'')} · ACH ${esc(p.ach_order_number||'')} · ${dateFmt(p.transaction_at)}</small></div>${statusHtml(p.match_status)}</div><div class="record-meta"><span>${esc(p.match_reason||'Requiere vinculación manual')}</span></div><div class="admin-actions"><button data-match-payment="${p.id}">Vincular a solicitud</button></div></div>`).join('')||empty('No hay pagos ACH ambiguos.');bindAdminActions()}else{const{data,error}=await sb.from('orders').select('id,order_code,customer_email,status,payment_method,total_amount,created_at,requires_manual_action').in('status',['PAID','MANUAL_REQUIRED','AWAITING_CODE','PROCESSING','ERROR']).order('created_at',{ascending:true}).limit(100);$('adminContent').innerHTML=error?err(error):(data||[]).map(o=>`<div class="record"><div class="record-top"><div><b>${esc(o.order_code)} · ${money(o.total_amount)}</b><small>${esc(o.customer_email)} · ${esc(o.payment_method)} · ${dateFmt(o.created_at)}</small></div>${statusHtml(o.status)}</div><div class="admin-actions"><button data-order-status="PROCESSING" data-id="${o.id}">Procesando</button><button data-order-status="DELIVERED" data-id="${o.id}">Entregado</button><button data-order-status="ERROR" data-id="${o.id}">Error</button></div></div>`).join('')||empty('No hay pedidos pendientes de gestión.');bindAdminActions()}}
function empty(t){return `<div class="record"><small>${esc(t)}</small></div>`}function err(e){return `<div class="notice error">${esc(e.message)}</div>`}
function bindAdminActions(){$('adminContent').querySelectorAll('[data-topup-action]').forEach(b=>b.onclick=()=>adminReviewTopup(b.dataset.id,b.dataset.topupAction));$('adminContent').querySelectorAll('[data-order-status]').forEach(b=>b.onclick=()=>adminOrderStatus(b.dataset.id,b.dataset.orderStatus));$('adminContent').querySelectorAll('[data-match-payment]').forEach(b=>b.onclick=()=>adminMatchPrompt(b.dataset.matchPayment))}
async function adminReviewTopup(id,action){if(!confirm(`${action==='APPROVE'?'Aprobar':'Rechazar'} esta solicitud?`))return;const{error}=await sb.rpc('admin_review_wallet_topup',{p_request_id:id,p_action:action});if(error)alert(error.message);loadAdmin()}
async function adminOrderStatus(id,status){const note=prompt('Nota Admin opcional:','')??null;const{error}=await sb.rpc('admin_update_order_status',{p_order_id:id,p_new_status:status,p_admin_note:note});if(error)alert(error.message);loadAdmin()}
async function adminMatchPrompt(eventId){const{data,error}=await sb.from('wallet_topup_requests').select('id,payment_reference,amount,created_at').eq('status','PENDING').order('created_at',{ascending:true}).limit(30);if(error){alert(error.message);return}if(!data?.length){alert('No hay solicitudes PENDING para vincular.');return}const menu=data.map((r,i)=>`${i+1}. ${r.payment_reference} · ${money(r.amount)}`).join('\n');const pick=Number(prompt(`Elige el número de solicitud:\n${menu}`));if(!pick||!data[pick-1])return;const{error:e}=await sb.rpc('admin_match_bank_payment',{p_event_id:eventId,p_request_id:data[pick-1].id});if(e)alert(e.message);loadAdmin()}

function quoteWhatsApp(){window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent('Hola, FRENCH STORE. No encontré el producto que busco y quisiera una cotización.')}`,'_blank','noopener,noreferrer')}
function qrWhatsApp(){if(!lastQrOrder)return;window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(`Hola, ya realicé el pago del pedido ${lastQrOrder.order_code} por ${money(lastQrOrder.total)}.`)}`,'_blank','noopener,noreferrer')}

function wireUI(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{category=b.dataset.category;renderCategoryTabs();renderCatalog();navigate('tienda')});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeModal(m.id)});$('authButton').onclick=()=>session?navigate('perfil'):openModal('authModal');$('cartButton').onclick=$('cartInline').onclick=()=>{renderCart();openModal('cartModal')};$('loginSubmit').onclick=signIn;$('logoutButton').onclick=signOut;$('requestTopup').onclick=requestTopup;$('refreshWallet').onclick=loadWallet;$('refreshOrders').onclick=loadOrders;$('checkoutWallet').onclick=()=>checkout('wallet');$('checkoutQR').onclick=()=>checkout('qr');$('whatsappQuote').onclick=$('floatingWhatsapp').onclick=quoteWhatsApp;$('qrWhatsapp').onclick=qrWhatsApp;$('openAdmin').onclick=()=>navigate('admin');$('refreshAdmin').onclick=loadAdmin;document.querySelectorAll('[data-admin-tab]').forEach(b=>b.onclick=()=>{adminTab=b.dataset.adminTab;document.querySelectorAll('[data-admin-tab]').forEach(x=>x.classList.toggle('active',x===b));loadAdmin()});document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal.open').forEach(m=>closeModal(m.id))})}

async function addSignupButton(){const btn=document.createElement('button');btn.className='secondary-btn full';btn.style.marginTop='8px';btn.textContent='Crear cuenta';btn.onclick=signUp;$('loginSubmit').after(btn)}

async function init(){wireUI();addSignupButton();renderCartCounters();await Promise.all([loadProducts(),refreshSession()]);sb.auth.onAuthStateChange(async(_event,newSession)=>{await refreshSession(newSession);if(newSession)closeModal('authModal')})}
init();